config/routes.rb
Crackle::Application.routes.draw do
  devise_for :users

  get "/users" => "home#users"
  root "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :username
  validates_uniqueness_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: :index

  def index
  end

  def users
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
.well
  %h1 Hello, #{current_user.username}
  %h3 Your email is: #{current_user.email}

app/views/home/users.html.haml
- if @users
  %h2 Registered users
  %ul.list-group
    - @users.each do |user|
      %li.list-group-item= user.username
- else
  %h2 No users yet

app/views/layouts/application.html.haml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
%html
  %head
    %title Crackle
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
%body
  %header.navbar.navbar-inverse.navbar-fixed-top
    .container
      .collapse.navbar-collapse.navbar-ex1-collapse
        %ul.nav.navbar-nav
          %li= link_to "Github project", "https://github.com/stdashulya/crackle"
          %li= link_to "Users", users_path
          - if user_signed_in?
            %li= link_to "Edit profile", edit_registration_path(current_user)
        %ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            %li= link_to "Cancel my account", registration_path(current_user), method: :delete
            %li= link_to "Log out", destroy_session_path(current_user), method: :delete
          - else
            %li= link_to "Sign in", new_user_session_path
            %li= link_to "Sign up", new_user_registration_path
  #main.container
    .row
      .col-md-3
      .col-md-6
        = yield
      .col-md-3